// action type for authentication
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'


export const CART_ADD = 'CART_ADD'
export const CART_REMOVE = 'CART_REMOVE'
export const CART_VISIBLE = 'CART_VISIBLE'
export const SET_SELECTED = 'SET_SELECTED'
export const RECEIVE_DATA = 'RECIEVE_DATA'
export const CART_FETCH = 'CART_FETCH'
export const DESTINATIONHOT_SEARCH = 'DESTINATIONHOT_SEARCH'
export const DESTINATIONHOT_SEARCHFETCH = 'DESTINATIONHOT_SEARCHFETCH'
export const RECEIVEMAP_DATA = 'RECEIVEMAP_DATA'
export const RECEIVEPRODUCT_DATA = 'RECEIVEPRODUCT_DATA'


export const ADD_PHOTO = 'ADD_PHOTO'
export const DEL_PHOTO = 'DEL_PHOTO'
export const EDIT_INFO = 'EDIT_INFO'
export const RECIEVE_INFO = 'RECIEVE_INFO'
export const LOAD_POST = 'LOAD_POST'

